
<!DOCTYPE html>
<html lang="en">
  
<head>
    
<meta charset="utf-8">
    
<title>Medi+ V10 (HMIS Global)| www.hmisglobal.com</title>
    
<meta name="viewport" content="width=device-width, initial-scale=1.0">
    
<meta name="description" content="">
    
<meta name="author" content="">

    
<script language="JavaScript" src="popups/pop-up.js"></script>
<link rel=StyleSheet href="popups/pop-upstyle.css" type="text/css" media="white">






<script type="text/javascript" src="ajax-menu.files/dmenu.js"></script>
  <style type="text/css">#deluxeMenu{display:none}</style>

<noscript><link type="text/css" href="ajax-menu.files/style.css" rel="stylesheet"></noscript>
  














<!-- Le styles -->
    
<link href="bootstrap/css/bootstrap.min.css" rel="stylesheet">
    
<style type="text/css">
	body {
		padding-top: 60px;
		padding-bottom: 40px;
	}
	.sidebar-nav {
		padding: 9px 0;
	}
	.nav
	{
		margin-bottom:10px;
	}	
	.accordion-inner a {
		font-size: 13px;
		font-family:tahoma;
	}
	.alert {
		padding:8px 14px 8px 14px;
	}
    </style>

    
<!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    
<![endif]-->

  
</head>

  
<!--body-->

<body >


<link rel="stylesheet" href="css/style.css" type="text/css" media="white">

<!-- Deluxe Menu -->

<!-- Code for Deluxe Menu Items. Generated by Deluxe Tuner -->







    
<div class="navbar navbar-inverse navbar-fixed-top">
      
<div class="navbar-inner">
        
<div class="container-fluid">
          
<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            
<span class="icon-bar"></span>
            
<span class="icon-bar"></span>
            
<span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Medi+ V10 (HMIS Global)</a>
          <div class="nav-collapse collapse">
            
<p class="navbar-text pull-right">
              <a target="_blank" href="http://www.hmisglobal.com" class="navbar-link">www.hmisglobal.com</a>
            </p>
            <!--ul class="nav" id="deluxeMenu"-->
              <ul id="deluxeMenu">

              <!--li><a target="_blank" href="http://www.hmisglobal.com">Home</a></li>
              <li class="active"><a href="http://www.hmisglobal.com/setup">Setup</a></li>
              <li><a target="_blank" href="http://www.hmisglobal.com/setup">FAQ</a></li>              
              <li><a target="_blank" href="http://www.hmisglobal/docs">Docs</a></li>
              <li><a href="#contact">Contact</a></li-->



              <li><a href=javascript:popcontact('index3.php')>Home</a></li>
	<li><a href="#"><span>Hospital Settings </span></a><a href="info1.html" style="display: none;"></a></li><li><a href="#"><span>Patient Billing     </span></a><a href="info.html" style="display: none;"></a></li>
	
              <li><a href="#"><span>Stocks Ledger</span></a><a href="stocks_ledger.html" style="display: none;"></a></li>
	<li><a href="http://deluxe-menu.com/order-purchase.html" target="_blank">Purchase</a></li>
	<li><a href="#">Contact Us</a></li>
</ul>

              <!-- End of Code for Deluxe Menu Items -->
              <!-- 
<noscript><p style="display:none"><a href="http://deluxe-menu.com">java dropdown menu by Deluxe-Menu.com</a></p></noscript>
          (c) 2009, Deluxe-Menu.com -->


              <script type="text/javascript" src="ajax-menu.files/data.js"></script>





            <!--/ul-->



          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

	
    
<div class="container-fluid">
      <div class="row-fluid">
        <div class="span2">

			
<div class="accordion" id="accordion_menu">
					
						
<div class="accordion-group">
						
<div class="accordion-heading">
						



<!--a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion_menu" href="info.html"-->
<a href=javascript:popcontact('users_register.php')><strong><img src='images/user_register.jpg' alt='statement' height='40' width='200'></strong></a>
						</div>
<div id="collapseappearence" class="accordion-body collapse">
							<div class="accordion-inner">
								
<a href='demos/appearence/alternate-row.php' onclick="jQuery('#span_version').hide();;jQuery('#code').load('index.php?file=/appearence/alternate-row.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Alternate Row </a><br/><a href='http://www.phpgrid.org/demo/demos/appearence/bar-graph.php' onclick="jQuery('#div_version').html('(*) Available in Licensed Version. Currently loaded from www.phpgrid.org');jQuery('#span_version').show();;jQuery('#code').load('index.php?file=/appearence/bar-graph.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Bar Graph <font color='red'>*</font> </a><br/><a href='http://www.phpgrid.org/demo/demos/appearence/calc-column.php' onclick="jQuery('#div_version').html('(*) Available in Licensed Version. Currently loaded from www.phpgrid.org');jQuery('#span_version').show();;jQuery('#code').load('index.php?file=/appearence/calc-column.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Calc Column <font color='red'>*</font> </a><br/><a href='http://www.phpgrid.org/demo/demos/appearence/conditional-data.php' onclick="jQuery('#div_version').html('(*) Available in Licensed Version. Currently loaded from www.phpgrid.org');jQuery('#span_version').show();;jQuery('#code').load('index.php?file=/appearence/conditional-data.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Conditional Data <font color='red'>*</font> </a><br/><a href='http://www.phpgrid.org/demo/demos/appearence/conditional-format.php' onclick="jQuery('#div_version').html('(*) Available in Licensed Version. Currently loaded from www.phpgrid.org');jQuery('#span_version').show();;jQuery('#code').load('index.php?file=/appearence/conditional-format.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Conditional Format <font color='red'>*</font> </a><br/><a href='http://www.phpgrid.org/demo/demos/appearence/custom-grid-button.php' onclick="jQuery('#div_version').html('(*) Available in Licensed Version. Currently loaded from www.phpgrid.org');jQuery('#span_version').show();;jQuery('#code').load('index.php?file=/appearence/custom-grid-button.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Custom Grid Button <font color='red'>*</font> </a><br/><a href='http://www.phpgrid.org/demo/demos/appearence/custom-row-button.php' onclick="jQuery('#div_version').html('(*) Available in Licensed Version. Currently loaded from www.phpgrid.org');jQuery('#span_version').show();;jQuery('#code').load('index.php?file=/appearence/custom-row-button.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Custom Row Button <font color='red'>*</font> </a><br/><a href='http://www.phpgrid.org/demo/demos/appearence/dropdown-callback.php' onclick="jQuery('#div_version').html('(*) Available in Licensed Version. Currently loaded from www.phpgrid.org');jQuery('#span_version').show();;jQuery('#code').load('index.php?file=/appearence/dropdown-callback.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Dropdown Callback <font color='red'>*</font> </a><br/><a href='http://www.phpgrid.org/demo/demos/appearence/dropdown-dependent.php' onclick="jQuery('#div_version').html('(*) Available in Licensed Version. Currently loaded from www.phpgrid.org');jQuery('#span_version').show();;jQuery('#code').load('index.php?file=/appearence/dropdown-dependent.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Dropdown Dependent <font color='red'>*</font> </a><br/><a href='http://www.phpgrid.org/demo/demos/appearence/dropdown.php' onclick="jQuery('#div_version').html('(*) Available in Licensed Version. Currently loaded from www.phpgrid.org');jQuery('#span_version').show();;jQuery('#code').load('index.php?file=/appearence/dropdown.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Dropdown <font color='red'>*</font> </a><br/><a href='http://www.phpgrid.org/demo/demos/appearence/excel-blank-rows.php' onclick="jQuery('#div_version').html('(*) Available in Licensed Version. Currently loaded from www.phpgrid.org');jQuery('#span_version').show();;jQuery('#code').load('index.php?file=/appearence/excel-blank-rows.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Excel Blank Rows <font color='red'>*</font> </a><br/><a href='http://www.phpgrid.org/demo/demos/appearence/excel-view.php' onclick="jQuery('#div_version').html('(*) Available in Licensed Version. Currently loaded from www.phpgrid.org');jQuery('#span_version').show();;jQuery('#code').load('index.php?file=/appearence/excel-view.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Excel View <font color='red'>*</font> </a><br/><a href='demos/appearence/external-link.php' onclick="jQuery('#span_version').hide();;jQuery('#code').load('index.php?file=/appearence/external-link.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> External Link </a><br/><a href='http://www.phpgrid.org/demo/demos/appearence/footer-row.php' onclick="jQuery('#div_version').html('(*) Available in Licensed Version. Currently loaded from www.phpgrid.org');jQuery('#span_version').show();;jQuery('#code').load('index.php?file=/appearence/footer-row.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Footer Row <font color='red'>*</font> </a><br/><a href='http://www.phpgrid.org/demo/demos/appearence/frozen-columns.php' onclick="jQuery('#div_version').html('(*) Available in Licensed Version. Currently loaded from www.phpgrid.org');jQuery('#span_version').show();;jQuery('#code').load('index.php?file=/appearence/frozen-columns.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Frozen Columns <font color='red'>*</font> </a><br/><a href='http://www.phpgrid.org/demo/demos/appearence/group-headers.php' onclick="jQuery('#div_version').html('(*) Available in Licensed Version. Currently loaded from www.phpgrid.org');jQuery('#span_version').show();;jQuery('#code').load('index.php?file=/appearence/group-headers.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Group Headers <font color='red'>*</font> </a><br/><a href='http://www.phpgrid.org/demo/demos/appearence/grouping.php' onclick="jQuery('#div_version').html('(*) Available in Licensed Version. Currently loaded from www.phpgrid.org');jQuery('#span_version').show();;jQuery('#code').load('index.php?file=/appearence/grouping.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Grouping <font color='red'>*</font> </a><br/><a href='http://www.phpgrid.org/demo/demos/appearence/image.php' onclick="jQuery('#div_version').html('(*) Available in Licensed Version. Currently loaded from www.phpgrid.org');jQuery('#span_version').show();;jQuery('#code').load('index.php?file=/appearence/image.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Image <font color='red'>*</font> </a><br/><a href='http://www.phpgrid.org/demo/demos/appearence/persist-settings.php' onclick="jQuery('#div_version').html('(*) Available in Licensed Version. Currently loaded from www.phpgrid.org');jQuery('#span_version').show();;jQuery('#code').load('index.php?file=/appearence/persist-settings.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Persist Settings <font color='red'>*</font> </a><br/><a href='http://www.phpgrid.org/demo/demos/appearence/row-button-edit-dialog.php' onclick="jQuery('#div_version').html('(*) Available in Licensed Version. Currently loaded from www.phpgrid.org');jQuery('#span_version').show();;jQuery('#code').load('index.php?file=/appearence/row-button-edit-dialog.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Row Button Edit Dialog <font color='red'>*</font> </a><br/><a href='demos/appearence/themes.php' onclick="jQuery('#span_version').hide();;jQuery('#code').load('index.php?file=/appearence/themes.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Themes </a><br/><a href='http://www.phpgrid.org/demo/demos/appearence/toolbar-button.php' onclick="jQuery('#div_version').html('(*) Available in Licensed Version. Currently loaded from www.phpgrid.org');jQuery('#span_version').show();;jQuery('#code').load('index.php?file=/appearence/toolbar-button.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Toolbar Button <font color='red'>*</font> </a><br/><a href='demos/appearence/twitter-bootstrap.php' onclick="jQuery('#span_version').hide();;jQuery('#code').load('index.php?file=/appearence/twitter-bootstrap.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Twitter Bootstrap </a><br/>							
</div>
						
</div>				
						
</div>				
						
						
<div class="accordion-group">
						
<div class="accordion-heading">
						
<!--a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion_menu" href="#collapseediting"-->
<a href=javascript:popcontact('debtors_register.php')><strong><img src='images/account_receivables.jpg' alt='statement' height='40' width='200'></strong></a>
						</div>
<div id="collapseediting" class="accordion-body collapse">
							<div class="accordion-inner">
								
<a href='http://www.phpgrid.org/demo/demos/editing/bulk-edit.php' onclick="jQuery('#div_version').html('(*) Available in Licensed Version. Currently loaded from www.phpgrid.org');jQuery('#span_version').show();;jQuery('#code').load('index.php?file=/editing/bulk-edit.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Bulk Edit <font color='red'>*</font> </a><br/><a href='http://www.phpgrid.org/demo/demos/editing/clone-row.php' onclick="jQuery('#div_version').html('(*) Available in Licensed Version. Currently loaded from www.phpgrid.org');jQuery('#span_version').show();;jQuery('#code').load('index.php?file=/editing/clone-row.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Clone Row <font color='red'>*</font> </a><br/><a href='http://www.phpgrid.org/demo/demos/editing/column-access.php' onclick="jQuery('#div_version').html('(*) Available in Licensed Version. Currently loaded from www.phpgrid.org');jQuery('#span_version').show();;jQuery('#code').load('index.php?file=/editing/column-access.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Column Access <font color='red'>*</font> </a><br/><a href='http://www.phpgrid.org/demo/demos/editing/custom-events.php' onclick="jQuery('#div_version').html('(*) Available in Licensed Version. Currently loaded from www.phpgrid.org');jQuery('#span_version').show();;jQuery('#code').load('index.php?file=/editing/custom-events.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Custom Events <font color='red'>*</font> </a><br/><a href='demos/editing/db-table-grid.php' onclick="jQuery('#span_version').hide();;jQuery('#code').load('index.php?file=/editing/db-table-grid.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Db Table Grid </a><br/><a href='http://www.phpgrid.org/demo/demos/editing/default-edit.php' onclick="jQuery('#div_version').html('(*) Available in Licensed Version. Currently loaded from www.phpgrid.org');jQuery('#span_version').show();;jQuery('#code').load('index.php?file=/editing/default-edit.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Default Edit <font color='red'>*</font> </a><br/><a href='http://www.phpgrid.org/demo/demos/editing/dialog-layout.php' onclick="jQuery('#div_version').html('(*) Available in Licensed Version. Currently loaded from www.phpgrid.org');jQuery('#span_version').show();;jQuery('#code').load('index.php?file=/editing/dialog-layout.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Dialog Layout <font color='red'>*</font> </a><br/><a href='http://www.phpgrid.org/demo/demos/editing/file-upload.php' onclick="jQuery('#div_version').html('(*) Available in Licensed Version. Currently loaded from www.phpgrid.org');jQuery('#span_version').show();;jQuery('#code').load('index.php?file=/editing/file-upload.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> File Upload <font color='red'>*</font> </a><br/><a href='demos/editing/index.php' onclick="jQuery('#span_version').hide();;jQuery('#code').load('index.php?file=/editing/index.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Index </a><br/><a href='http://www.phpgrid.org/demo/demos/editing/inline-add.php' onclick="jQuery('#div_version').html('(*) Available in Licensed Version. Currently loaded from www.phpgrid.org');jQuery('#span_version').show();;jQuery('#code').load('index.php?file=/editing/inline-add.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Inline Add <font color='red'>*</font> </a><br/><a href='http://www.phpgrid.org/demo/demos/editing/js-validation-form.php' onclick="jQuery('#div_version').html('(*) Available in Licensed Version. Currently loaded from www.phpgrid.org');jQuery('#span_version').show();;jQuery('#code').load('index.php?file=/editing/js-validation-form.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Js Validation Form <font color='red'>*</font> </a><br/><a href='demos/editing/js-validation.php' onclick="jQuery('#span_version').hide();;jQuery('#code').load('index.php?file=/editing/js-validation.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Js Validation </a><br/><a href='http://www.phpgrid.org/demo/demos/editing/server-errors.php' onclick="jQuery('#div_version').html('(*) Available in Licensed Version. Currently loaded from www.phpgrid.org');jQuery('#span_version').show();;jQuery('#code').load('index.php?file=/editing/server-errors.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Server Errors <font color='red'>*</font> </a><br/><a href='http://www.phpgrid.org/demo/demos/editing/server-validation.php' onclick="jQuery('#div_version').html('(*) Available in Licensed Version. Currently loaded from www.phpgrid.org');jQuery('#span_version').show();;jQuery('#code').load('index.php?file=/editing/server-validation.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Server Validation <font color='red'>*</font> </a><br/>							
</div>
						
</div>				
						
</div>				
						
						
<div class="accordion-group">
						
<div class="accordion-heading">
						
<!--a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion_menu" href="#collapseexport"><strong-->
<a href=javascript:popcontact('suppliers_register.php')><strong><img src='images/account_payables.jpg' alt='statement' height='40' width='200'></strong></a>
						</div>
<div id="collapseexport" class="accordion-body collapse">
							<div class="accordion-inner">
								
<a href='http://www.phpgrid.org/demo/demos/export/export-all.php' onclick="jQuery('#div_version').html('(*) Available in Licensed Version. Currently loaded from www.phpgrid.org');jQuery('#span_version').show();;jQuery('#code').load('index.php?file=/export/export-all.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Export All <font color='red'>*</font> </a><br/><a href='http://www.phpgrid.org/demo/demos/export/export-csv.php' onclick="jQuery('#div_version').html('(*) Available in Licensed Version. Currently loaded from www.phpgrid.org');jQuery('#span_version').show();;jQuery('#code').load('index.php?file=/export/export-csv.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Export Csv <font color='red'>*</font> </a><br/><a href='http://www.phpgrid.org/demo/demos/export/export-custom.php' onclick="jQuery('#div_version').html('(*) Available in Licensed Version. Currently loaded from www.phpgrid.org');jQuery('#span_version').show();;jQuery('#code').load('index.php?file=/export/export-custom.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Export Custom <font color='red'>*</font> </a><br/><a href='http://www.phpgrid.org/demo/demos/export/export-excel.php' onclick="jQuery('#div_version').html('(*) Available in Licensed Version. Currently loaded from www.phpgrid.org');jQuery('#span_version').show();;jQuery('#code').load('index.php?file=/export/export-excel.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Export Excel <font color='red'>*</font> </a><br/><a href='http://www.phpgrid.org/demo/demos/export/export-pdf-html.php' onclick="jQuery('#div_version').html('(*) Available in Licensed Version. Currently loaded from www.phpgrid.org');jQuery('#span_version').show();;jQuery('#code').load('index.php?file=/export/export-pdf-html.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Export Pdf Html <font color='red'>*</font> </a><br/><a href='http://www.phpgrid.org/demo/demos/export/export-pdf.php' onclick="jQuery('#div_version').html('(*) Available in Licensed Version. Currently loaded from www.phpgrid.org');jQuery('#span_version').show();;jQuery('#code').load('index.php?file=/export/export-pdf.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Export Pdf <font color='red'>*</font> </a><br/>							
</div>
						
</div>				
						
</div>				
						
						
<div class="accordion-group">
						
<div class="accordion-heading">
						
<a href=javascript:popcontact('doctors_register.php')><strong><img src='images/doctors_register.jpg' alt='statement' height='40' width='200'></strong></a>						
						</div>
<div id="collapseintegrations" class="accordion-body collapse">
							<div class="accordion-inner">
								
<a href='http://www.phpgrid.org/demo/demos/integrations/autocomplete.php' onclick="jQuery('#div_version').html('(*) Available in Licensed Version. Currently loaded from www.phpgrid.org');jQuery('#span_version').show();;jQuery('#code').load('index.php?file=/integrations/autocomplete.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Autocomplete <font color='red'>*</font> </a><br/><a href='http://www.phpgrid.org/demo/demos/integrations/datepicker.php' onclick="jQuery('#div_version').html('(*) Available in Licensed Version. Currently loaded from www.phpgrid.org');jQuery('#span_version').show();;jQuery('#code').load('index.php?file=/integrations/datepicker.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Datepicker <font color='red'>*</font> </a><br/><a href='http://www.phpgrid.org/demo/demos/integrations/datetimepicker.php' onclick="jQuery('#div_version').html('(*) Available in Licensed Version. Currently loaded from www.phpgrid.org');jQuery('#span_version').show();;jQuery('#code').load('index.php?file=/integrations/datetimepicker.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Datetimepicker <font color='red'>*</font> </a><br/><a href='http://www.phpgrid.org/demo/demos/integrations/dropdown-select2.php' onclick="jQuery('#div_version').html('(*) Available in Licensed Version. Currently loaded from www.phpgrid.org');jQuery('#span_version').show();;jQuery('#code').load('index.php?file=/integrations/dropdown-select2.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Dropdown Select2 <font color='red'>*</font> </a><br/><a href='http://www.phpgrid.org/demo/demos/integrations/fancy-box.php' onclick="jQuery('#div_version').html('(*) Available in Licensed Version. Currently loaded from www.phpgrid.org');jQuery('#span_version').show();;jQuery('#code').load('index.php?file=/integrations/fancy-box.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Fancy Box <font color='red'>*</font> </a><br/><a href='http://www.phpgrid.org/demo/demos/integrations/html-editor.php' onclick="jQuery('#div_version').html('(*) Available in Licensed Version. Currently loaded from www.phpgrid.org');jQuery('#span_version').show();;jQuery('#code').load('index.php?file=/integrations/html-editor.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Html Editor <font color='red'>*</font> </a><br/><a href='http://www.phpgrid.org/demo/demos/integrations/tag-it.php' onclick="jQuery('#div_version').html('(*) Available in Licensed Version. Currently loaded from www.phpgrid.org');jQuery('#span_version').show();;jQuery('#code').load('index.php?file=/integrations/tag-it.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Tag It <font color='red'>*</font> </a><br/><a href='http://www.phpgrid.org/demo/demos/integrations/timepicker.php' onclick="jQuery('#div_version').html('(*) Available in Licensed Version. Currently loaded from www.phpgrid.org');jQuery('#span_version').show();;jQuery('#code').load('index.php?file=/integrations/timepicker.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Timepicker <font color='red'>*</font> </a><br/>							
</div>
						
</div>				
						
</div>				
						
						
<div class="accordion-group">
						
<div class="accordion-heading">
						
<a href=javascript:popcontact('stocks_register.php')><strong><img src='images/stocks_register.jpg' alt='statement' height='40' width='200'></strong></a>						
						</div>
<div id="collapseloading" class="accordion-body collapse">
							<div class="accordion-inner">
								
<a href='http://www.phpgrid.org/demo/demos/loading/db-layer-access.php' onclick="jQuery('#div_version').html('(*) Available in Licensed Version. Currently loaded from www.phpgrid.org');jQuery('#span_version').show();;jQuery('#code').load('index.php?file=/loading/db-layer-access.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Db Layer Access <font color='red'>*</font> </a><br/><a href='http://www.phpgrid.org/demo/demos/loading/db-layer-oracle-join.php' onclick="jQuery('#div_version').html('(*) Available in Licensed Version. Currently loaded from www.phpgrid.org');jQuery('#span_version').show();;jQuery('#code').load('index.php?file=/loading/db-layer-oracle-join.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Db Layer Oracle Join <font color='red'>*</font> </a><br/><a href='demos/loading/db-layer-oracle.php' onclick="jQuery('#span_version').hide();;jQuery('#code').load('index.php?file=/loading/db-layer-oracle.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Db Layer Oracle </a><br/><a href='demos/loading/db-layer-pgsql.php' onclick="jQuery('#span_version').hide();;jQuery('#code').load('index.php?file=/loading/db-layer-pgsql.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Db Layer Pgsql </a><br/><a href='demos/loading/db-layer-sqlsvr.php' onclick="jQuery('#span_version').hide();;jQuery('#code').load('index.php?file=/loading/db-layer-sqlsvr.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Db Layer Sqlsvr </a><br/><a href='demos/loading/load-array.php' onclick="jQuery('#span_version').hide();;jQuery('#code').load('index.php?file=/loading/load-array.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Load Array </a><br/>							
</div>
						
</div>				
						
</div>				
						
						
<div class="accordion-group">
						
<div class="accordion-heading">
						
<a href=javascript:popcontact('gl_accounts_register.php')><strong><img src='images/gl_register.jpg' alt='statement' height='40' width='200'></strong></a>						
						</div>
<div id="collapsemaster-detail" class="accordion-body collapse">
							<div class="accordion-inner">
								
<a href='http://www.phpgrid.org/demo/demos/master-detail/master-detail-dropdown.php' onclick="jQuery('#div_version').html('(*) Available in Licensed Version. Currently loaded from www.phpgrid.org');jQuery('#span_version').show();;jQuery('#code').load('index.php?file=/master-detail/master-detail-dropdown.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Master Detail Dropdown <font color='red'>*</font> </a><br/><a href='http://www.phpgrid.org/demo/demos/master-detail/master-detail-fancy.php' onclick="jQuery('#div_version').html('(*) Available in Licensed Version. Currently loaded from www.phpgrid.org');jQuery('#span_version').show();;jQuery('#code').load('index.php?file=/master-detail/master-detail-fancy.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Master Detail Fancy <font color='red'>*</font> </a><br/><a href='http://www.phpgrid.org/demo/demos/master-detail/master-detail.php' onclick="jQuery('#div_version').html('(*) Available in Licensed Version. Currently loaded from www.phpgrid.org');jQuery('#span_version').show();;jQuery('#code').load('index.php?file=/master-detail/master-detail.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Master Detail <font color='red'>*</font> </a><br/><a href='http://www.phpgrid.org/demo/demos/master-detail/master-multi-detail.php' onclick="jQuery('#div_version').html('(*) Available in Licensed Version. Currently loaded from www.phpgrid.org');jQuery('#span_version').show();;jQuery('#code').load('index.php?file=/master-detail/master-multi-detail.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Master Multi Detail <font color='red'>*</font> </a><br/><a href='http://www.phpgrid.org/demo/demos/master-detail/multi-subgrid.php' onclick="jQuery('#div_version').html('(*) Available in Licensed Version. Currently loaded from www.phpgrid.org');jQuery('#span_version').show();;jQuery('#code').load('index.php?file=/master-detail/multi-subgrid.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Multi Subgrid <font color='red'>*</font> </a><br/><a href='http://www.phpgrid.org/demo/demos/master-detail/multiple-grids.php' onclick="jQuery('#div_version').html('(*) Available in Licensed Version. Currently loaded from www.phpgrid.org');jQuery('#span_version').show();;jQuery('#code').load('index.php?file=/master-detail/multiple-grids.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Multiple Grids <font color='red'>*</font> </a><br/><a href='http://www.phpgrid.org/demo/demos/master-detail/multiple-tab-grids.php' onclick="jQuery('#div_version').html('(*) Available in Licensed Version. Currently loaded from www.phpgrid.org');jQuery('#span_version').show();;jQuery('#code').load('index.php?file=/master-detail/multiple-tab-grids.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Multiple Tab Grids <font color='red'>*</font> </a><br/><a href='http://www.phpgrid.org/demo/demos/master-detail/nested-master-detail.php' onclick="jQuery('#div_version').html('(*) Available in Licensed Version. Currently loaded from www.phpgrid.org');jQuery('#span_version').show();;jQuery('#code').load('index.php?file=/master-detail/nested-master-detail.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Nested Master Detail <font color='red'>*</font> </a><br/><a href='http://www.phpgrid.org/demo/demos/master-detail/subgrid.php' onclick="jQuery('#div_version').html('(*) Available in Licensed Version. Currently loaded from www.phpgrid.org');jQuery('#span_version').show();;jQuery('#code').load('index.php?file=/master-detail/subgrid.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Subgrid <font color='red'>*</font> </a><br/>							
</div>
						
</div>				
						
</div>				
<divclass="accordion-group">
						
<div class="accordion-heading">
						
<a href=javascript:popcontact('revenue_register.php')><strong><img src='images/revenue_register.jpg' alt='statement' height='200' width='200'></strong></a>	</div>
<div id="collapsemisc" class="accordion-body collapse">
							<div class="accordion-inner">
								

<a href='http://www.phpgrid.org/demo/demos/misc/arabic-rtl.php' onclick="jQuery('#div_version').html('(*) Available in Licensed Version. Currently loaded from www.phpgrid.org');jQuery('#span_version').show();;jQuery('#code').load('index.php?file=/misc/arabic-rtl.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Arabic Rtl <font color='red'>*</font> </a><br/><a href='demos/misc/example-all.php' onclick="jQuery('#span_version').hide();;jQuery('#code').load('index.php?file=/misc/example-all.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Example All </a><br/><a href='http://www.phpgrid.org/demo/demos/misc/example-full.php' onclick="jQuery('#div_version').html('(*) Available in Licensed Version. Currently loaded from www.phpgrid.org');jQuery('#span_version').show();;jQuery('#code').load('index.php?file=/misc/example-full.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Example Full <font color='red'>*</font> </a><br/><a href='http://www.phpgrid.org/demo/demos/misc/keep-vertical-scroll.php' onclick="jQuery('#div_version').html('(*) Available in Licensed Version. Currently loaded from www.phpgrid.org');jQuery('#span_version').show();;jQuery('#code').load('index.php?file=/misc/keep-vertical-scroll.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Keep Vertical Scroll <font color='red'>*</font> </a><br/><a href='demos/misc/localization.php' onclick="jQuery('#span_version').hide();;jQuery('#code').load('index.php?file=/misc/localization.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Localization </a><br/>							


</div>
						
</div>				
						
</div>				
						
						
<div class="accordion-group">

<a href=javascript:popcontact('property.php')><strong><img src='images/revenue_register.jpg' alt='statement' height='200' width='200'></strong></a>	</div>
<div id="collapsemisc" class="accordion-body collapse">
						
<div class="accordion-heading">
						
<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion_menu" href="#collapsesearch">

						  <strong>
</strong>
						</a>
						</div>







<div id="collapsesearch" class="accordion-body collapse">
							<div class="accordion-inner">
								
<a href='http://www.phpgrid.org/demo/demos/search/autofilter.php' onclick="jQuery('#div_version').html('(*) Available in Licensed Version. Currently loaded from www.phpgrid.org');jQuery('#span_version').show();;jQuery('#code').load('index.php?file=/search/autofilter.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Autofilter <font color='red'>*</font> </a><br/><a href='http://www.phpgrid.org/demo/demos/search/search-form.php' onclick="jQuery('#div_version').html('(*) Available in Licensed Version. Currently loaded from www.phpgrid.org');jQuery('#span_version').show();;jQuery('#code').load('index.php?file=/search/search-form.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Search Form <font color='red'>*</font> </a><br/><a href='http://www.phpgrid.org/demo/demos/search/search-onload.php' onclick="jQuery('#div_version').html('(*) Available in Licensed Version. Currently loaded from www.phpgrid.org');jQuery('#span_version').show();;jQuery('#code').load('index.php?file=/search/search-onload.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Search Onload <font color='red'>*</font> </a><br/><a href='http://www.phpgrid.org/demo/demos/search/search-template.php' onclick="jQuery('#div_version').html('(*) Available in Licensed Version. Currently loaded from www.phpgrid.org');jQuery('#span_version').show();;jQuery('#code').load('index.php?file=/search/search-template.php'); $('#grid-demo-tabs a:first').tab('show');" target='demo_frame'> Search Template <font color='red'>*</font> </a><br/>							
</div>
						
</div>				
						
</div>				
						
<img src='images/healthcare.png' alt='statement' height='400' width='200'>

<a href=javascript:popcontact('index2.php')><strong><img src='images/wards_register.jpg' alt='statement' height='40' width='200'></strong></a>
<a href=javascript:popcontact('beds_register.php')><strong><img src='images/beds_register.jpg' alt='statement' height='40' width='200'></strong></a>
<a href=javascript:popcontact('index2.php')><strong><img src='images/end_month.jpg' alt='statement' height='40' width='200'></strong></a>			
</div>	  

			








						















        <!--/div-->
<!--/span-->
        
<div class="span10">
          
<div class="row-fluid">
            
<div class="span12">
			
				
<ul class="nav nav-tabs" id="grid-demo-tabs">
					
<li class="active"><a href="#demo" data-toggle="tab">Patients Register</a></li>
<!--li><a href="#code" data-toggle="tab">Code</a></li-->
				</ul>
				
				
<div class="tab-content" id="grid-demo-tabs-content"><div id="demo" class="tab-pane fade in active"><span id="span_version" style="display:none">
		        		
<a id="div_version" style="margin-left:18px; width:100px; font-family: tahoma; padding:5px; background-color: #117AC0; letter-spacing:1px; color: white; text-decoration:underline;" target="_blank" href="http://www.phpgrid.org/download/"></a>
						
<br>
						
</span>						
						
<!--iframe onload="iframeLoaded(this)" name="demo_frame" frameborder="0" width="100%" height="600" src="demos/editing/index.php"-->
<iframe onload="iframeLoaded(this)" name="demo_frame" frameborder="0" width="100%" height="600" src="patients_reg.html">
</div>
				  
					
<div id="code" class="tab-pane fade">
</div>
				  
				
</div>

            
</div><!--/span-->
          
</div><!--/row-->
        
</div><!--/span-->
		
		
<div class="row-fluid">
			
<div class="span12">
			  
<div class="row-fluid">
				
<div class="alert alert-info">
					
<a name="contact"></a><h2>Technical Support</h2><p class="text-info">For technical support query, ask at our <a href="http://www.phpgrid.org/support">Support Center</a> </p>
				  <p>&copy; <a href="http://www.phpgrid.org">www.phpgrid.org</a> 2010-2015</p>
				
</div><!--/span-->
			  
</div><!--/row-->
			
</div><!--/span-->
		  
</div><!--/row-->
		  
      
</div><!--/row-->

		
<!-- Le javascript
		================================================== -->
		
<!-- Placed at the end of the document so the pages load faster -->
		
<script src="bootstrap/js/jquery.js"></script>
		
<script src="bootstrap/js/bootstrap.min.js"></script>
		
<script>$('#grid-demo-tabs a').click(function (e) {
	e.preventDefault();
			$(this).tab('show');
			})
			
			jQuery('#code').load('index.php?file=/editing/index.php'); >

			
function iframeLoaded(iFrameID) 
			{
				
if(iFrameID) 
				{
			        
iFrameID.height = "600px";
					
if(iFrameID.contentDocument){
						
iFrameID.height = iFrameID.contentDocument.body.offsetHeight + 35;
					
} else {
						
iFrameID.height = iFrameID.contentWindow.document.body.scrollHeight + 45 + "px";
					
}
				}
				
				
if (!stop)
				
setTimeout(function(){iframeLoaded(iFrameID,1);},1000);
			}
		
</script>
    
</div><!--/.fluid-container-->

	
<script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
	  ga('create', 'UA-50875146-1', 'phpgrid.org');
	  ga('send', 'pageview');
	
</script>
  
</body>
</html>
